remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: GLeDitor3 User manual
description: The on-line guide to the GLeDitor3 application: a small and simple programmer's editor for macOs
